.import __cur_on
.import __cur_off
.import __cur_move
.import __cur_set
.import __cur_up
.import __cur_down
.import __cur_right
.import __cur_left
.import __cur_toggle
.import __cur_setmin
.import __cur_setmax
.import __cur_unlimit

.scope cur
	on = __cur_on
	off = __cur_off
	move = __cur_move
	set = __cur_set
	up = __cur_up
	down = __cur_down
	right = __cur_right
	left = __cur_left
	toggle = __cur_toggle
	setmin = __cur_setmin
	setmax = __cur_setmax
	unlimit = __cur_unlimit
.endscope
