SCREEN=$400
SCREEN_W=40

.linecont +
.define row_addrs \
SCREEN, SCREEN+SCREEN_W, SCREEN+SCREEN_W*2, SCREEN+SCREEN_W*3,\
SCREEN+SCREEN_W*5, SCREEN+SCREEN_W*6, SCREEN+SCREEN_W*7, SCREEN+SCREEN_W*8,\
SCREEN+SCREEN_W*9, SCREEN+SCREEN_W*10, SCREEN+SCREEN_W*11, SCREEN+SCREEN_W*12,\
SCREEN+SCREEN_W*13, SCREEN+SCREEN_W*14, SCREEN+SCREEN_W*15, SCREEN+SCREEN_W*16,\
SCREEN+SCREEN_W*17, SCREEN+SCREEN_W*18, SCREEN+SCREEN_W*19, SCREEN+SCREEN_W*20,\
SCREEN+SCREEN_W*21, SCREEN+SCREEN_W*22, SCREEN+SCREEN_W*23, SCREEN+SCREEN_W*24
.linecont -

.export __c64_rowslo
.export __c64_rowshi
__c64_rowslo: .lobytes row_addrs
__c64_rowshi: .hibytes row_addrs
