.import __prefs_reverse_color
.import __prefs_text_color
.import __prefs_normal_color
.import __prefs_brkon_color
.import __prefs_brkoff_color
.import __prefs_success_color
.import __prefs_select_col
.import __prefs_palette

.scope prefs
	normal_color  = __prefs_normal_color
	text_color    = __prefs_text_color
	reverse_color = __prefs_reverse_color
	brkon_color   = __prefs_brkon_color
	brkoff_color  = __prefs_brkoff_color
	palette       = __prefs_palette
	success_color = __prefs_success_color
	select_color  = __prefs_select_col
.endscope
