;******************************************************************************
; PREFERENCES/COLORS

CUR_BLINK_SPEED = 250	; number of updates before blink

MAX_SEARCH_LEN = 16	; max size of search term in "find"

;******************************************************************************
; SOURCE FORMATTING
TAB_WIDTH = 10

;******************************************************************************
LINESIZE = 40	; the size of the buffer for 1 line on the screen

