.import __console_clear
.import __console_enter
.import __console_getch
.import __console_init
.import __console_int
.import __console_line
.import __console_outfile
.import __console_puts
.import __console_reenter
.import __console_quit

.scope con
	clear   = __console_clear
	enter   = __console_enter
	getch   = __console_getch
	init	= __console_init
	int	= __console_int
	line    = __console_line
	outfile = __console_outfile
	puts    = __console_puts
	reenter = __console_reenter
	quit    = __console_quit
.endscope
