.import __draw_hline
.import __draw_hiline
.import __draw_resetline
.import __draw_rvs_underline
.import __draw_scrollcolorsu
.import __draw_scrollcolorsd
.import __draw_coloroff
.import __draw_scrollcolorsd1

.scope draw
	hline          = __draw_hline
	hiline         = __draw_hiline
	resetline      = __draw_resetline
	rvs_underline  = __draw_rvs_underline
	scrollcolorsu  = __draw_scrollcolorsu
	scrollcolorsd  = __draw_scrollcolorsd
	scrollcolorsd1 = __draw_scrollcolorsd1
	coloroff       = __draw_coloroff
.endscope
