; NAVIGATION KEYS
K_LEFT      = $9d	; cursor left
K_RIGHT     = $1d	; cursor right
K_UP        = $91       ; cursor up
K_DOWN      = $11       ; cursor down
K_HOME      = $13	; HOME

K_UP_ARROW  = $5e	; up arrow

K_PREV_BUFF  = $3c	; <
K_NEXT_BUFF  = $3e	; >
K_NEW_BUFF   = $aa	; <C=> + n
K_CLOSE_BUFF = $ab	; <C=> + q

; GLOBAL INTERFACE KEYS
K_RETURN    = $0d	; RETURN
K_QUIT      = $5f	; <-
K_DEL       = $14	; DELETE

; EDITOR KEYS
K_SET_BREAKPOINT = $bf	; <C=> + B
K_ASM            = $86	; F3
K_ASM_DEBUG      = $8a  ; F4 (shift + F3)
K_ASM_FILE       = $b0	; C= + a
K_SHOW_BUFFERS   = $87	; F5
K_REFRESH        = $bc  ; <C=> + c
K_RENAME         = $b2  ; <C=> + r
K_DEBUG		 = $ac	; <C=> + d
K_DIR            = $b6  ; <C=> + l
K_LIST_SYMBOLS   = $b7  ; <C=> + y
K_FIND           = $2f	; /
K_GO             = $a5	; <C=> + g
K_GOTO_LINE	 = $a7	; <C=> + m
K_GOTO_BUFF1     = $81  ; <C=> + 1
K_GOTO_BUFF2     = $95  ; <C=> + 2
K_GOTO_BUFF3     = $96  ; <C=> + 3
K_GOTO_BUFF4     = $97  ; <C=> + 4
K_GOTO_BUFF5     = $98  ; <C+> + 5
K_GOTO_BUFF6     = $99  ; <C=> + 6
K_GOTO_BUFF7     = $9a  ; <C=> + 7
K_GOTO_BUFF8     = $9b  ; <C=> + 8
K_JUMPBACK       = $b9	; <C=> + o
K_JUMPFORWARD    = $a2	; <C=> + i
K_OPEN           = $b1	; <C=> + e
K_SCRATCH	 = $bd	; <C=> + x
K_SAVE 	         = $ae	; <C=> + s

; DEBUGGER KEYS
K_SRCVIEW      = $85	; F1
K_MEMVIEW      = $86	; F3
K_BRKVIEW      = $87	; F5
K_WATCHVIEW    = $88	; F7
K_SWAP_USERMEM = $20	; SPACE

;K_GO        = $a5	; <C=> + g
K_STEP      = $ad	; <C=> + z
K_STEPOVER  = $ae	; <C=> + s
K_TRACE     = $a3	; <C=> + t

K_SET_WATCH = $b3	; <C=>+W
