; NAVIGATION KEYS
K_LEFT      = $9d	; cursor left
K_RIGHT     = $1d	; cursor right

; GLOBAL INTERFACE KEYS
K_RETURN    = $0d	; RETURN
K_QUIT      = $5f	; <-

K_SET_BREAKPOINT = $bf	; <C=> + B

; DEBUGGER KEYS
K_SRCVIEW      = $85	; F1
K_MEMVIEW      = $86	; F3
K_BRKVIEW      = $87	; F5
K_WATCHVIEW    = $88	; F7
K_SWAP_USERMEM = $20	; SPACE

K_STEP      = $ad	; <C=> + z
K_STEPOVER  = $ae	; <C=> + s
K_GO        = $a5	; <C=> + g

K_SET_WATCH = $b3	; <C=>+W
