.import __label_add
.import __label_by_id
.import __label_clr
.import __label_clr_locals
.import __label_del
.import __label_find
.import __label_get_name
.import __label_get_addr
.import __label_is_local
.import __label_isvalid
.import __label_address
.import __label_num
.import __label_name_by_id

.scope lbl
	add = __label_add
	addr = __label_address
	by_id = __label_by_id
	clr = __label_clr
	clrlocals = __label_clr_locals
	del = __label_del
	find = __label_find
	getname = __label_get_name
	getaddr = __label_get_addr
	islocal = __label_is_local
	isvalid = __label_isvalid
	name_by_id = __label_name_by_id
	num = __label_num
.endscope
